### PR TITLE
More model validations

### PR DESCRIPTION
**Pull request by foFox**
I don't know where that file to localise error messages is.

### CODE REVIEW

**Comment by tsov** [comment]
Somewhere in the config folder. Its called en.yml

**Comment by tsov** [comment]
Ouh, i see there are conflicts on your branch. You have to pull development branch into your branch locally, to redolve the issues

**Comment by foFox** [comment]
Damn I haven't done it before. How do i pull to local dev ?

**Comment by tsov** [comment]
i call you in a little bit ;) facetime style

**Comment by foFox** [comment]
Grand :D

**Comment by tsov** [comment]
yay :+1:

**Pull request merged**
