### PR TITLE
Adding comments to event&place and offers to place

### PR DESCRIPTION
**Pull request by foFox**

### CODE REVIEW

**Comment by alankehoe** [comment]
This is looking really good, 
is it a complete redo of the server API ?

I need to start learning some ruby :)

Max we should look into having that meeting maybe next week ? I was so busy last week I never got around to asking Dave. Maybe next Wednesday ?

**Comment by foFox** [comment]
Yeah, we are porting to Rails due to the fact that previous solution was
getting way to verbose, mostly due to the fact that, there was a lot of
manual house keeping, to keep the DB consistent. We started moving some of
the controllers code onto the models, but the core issue still remained. On
Rails the API responses will be slower, but we don't know how much exactly.
On the flip side, we will learn Rails, and Rails devs are on high demand.

P.S
Rails are AWESOME. I was able to get up and running in few days. It just
DOES things, and you don't have to worry about details.

**Comment by alankehoe** [comment]
Well it looks very good i must say. Allot of apps are using rails so the response shouldn't be too much of a problem I would think. i see you have jumped on the Ruby bandwagon too now Rob ? i am trying to get some time to learn it in my spare time. I have allot of stuff to learn for work so its not going well at the moment :)

**Comment by foFox** [comment]
Yeah, Max wanted to some one to help out, so I am up for it :P

**Comment by alankehoe** [comment]
Cool 
I better get bite the bullet and learn it :)

I will talk to you later will be in touch about the meeting next week maybe parsons is up for next wednesday.

:+1:

**Pull request merged**
